### ISSUE TITLE
BrokenPipeError from dapp-runner almost immediately after starting

### ISSUE THREAD

**Issue by etam** [golemfactory/dapp-manager#65]
In `~/.local/share/dapp_manager/{some_id}/stderr` there is 
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dapp/dapp-manager/lib/python3.10/site-packages/dapp_runner/__main__.py", line 156, in <module>
    _cli()
  File "/home/dapp/dapp-manager/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/dapp/dapp-manager/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/dapp/dapp-manager/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dapp/dapp-manager/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dapp/dapp-manager/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/dapp/dapp-manager/lib/python3.10/site-packages/dapp_runner/__main__.py", line 125, in start
    start_runner(config_dict, dapp_dict, **kwargs)
  File "/home/dapp/dapp-manager/lib/python3.10/site-packages/dapp_runner/runner/__init__.py", line 140, in start_runner
    loop.run_until_complete(task)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/dapp/dapp-manager/lib/python3.10/site-packages/dapp_runner/runner/__init__.py", line 72, in _run_app
    logger.info(
Message: 'Starting app: %s, startup timeout: %s, maximum running time: %s'
Arguments: ('Simple, db-enabled web application.', datetime.timedelta(seconds=240), None)
```
dapp-manager version: 0.0.0a2
python version: 3.10.6
OS: Ubuntu 22.04.1 LTS

**Comment by shadeofblue** [comment]
@etam please upload full logs for both dapp-manager and dapp-runner

**Comment by shadeofblue** [comment]
(otherwise, so far, I couldn't reproduce this issue)

**Comment by shadeofblue** [comment]
okay, we were able to reproduce this issue

1. it's non-critical for now as the `dapp-runner` runs correctly anyway just emits unnecessarily worrying errors into the `stderr` file
2. it's most likely related to the fact that originally `dapp-manager` runs `dapp-runner` with stdout and sterr redirected to pipe to capture their output in case the runner fails to launch correctly
3. _may_ be related to `dapp-runner`'s logging configuration (dapp-runner first sets up logging and then wraps the execution with stdout/stderr redirects)
